### ISSUE TITLE
correct showing of the hosted OS window on Mac OS X

### ISSUE THREAD

**Issue by darvin** [dbalsom/martypc#10]
<img width="1080" alt="Screenshot 2023-06-26 at 7 42 38 PM" src="https://github.com/dbalsom/martypc/assets/309302/01b84c02-8641-4f5f-a30d-3be18867b1f1">

automatic scaling removing the empty dark space

**Comment by dbalsom** [comment]
Hey, I appreciate your interest, but if you are going to open issues please put a description or provide at least some basic information about your issue so I know what to address.

**Comment by darvin** [comment]
> Hey, I appreciate your interest, but if you are going to open issues please put a description or provide at least some basic information about your issue so I know what to address.

this issue is meant for future editing

**Comment by dbalsom** [comment]
MartyPC emulates a CGA card in a cycle-accurate way, recreating the entire NTSC field. This generates areas of overscan that would normally be hidden by the bezels of a real monitor and aren't commonly shown by other emulators. There will always be a black border in text modes (unless something has changed the background / overscan color), because there would be a black border on a real monitor. 

I plan to add a selectable display profile that will let you crop the overscan more tightly to better simulate the visible area of the screen, and add more scaling options. Right now scaling is in integer factors only to avoid bilinear filtering, so you are looking at both the emulated border and the border introduced by integer scaling.

**Comment by xcloudplatform** [comment]
> MartyPC emulates a CGA card in a cycle-accurate way, recreating the entire NTSC field. This generates areas of overscan that would normally be hidden by the bezels of a real monitor and aren't commonly shown by other emulators. There will always be a black border in text modes (unless something has changed the background / overscan color), because there would be a black border on a real monitor.
> 
> I plan to add a selectable display profile that will let you crop the overscan more tightly to better simulate the visible area of the screen, and add more scaling options. Right now scaling is in integer factors only to avoid bilinear filtering, so you are looking at both the emulated border and the border introduced by integer scaling.

sounds great! is it plausible to add a selectable profile file reloading in runtime (maybe on keybinding like "configs refresh"?

**Comment by dbalsom** [comment]
> sounds great! is it plausible to add a selectable profile file reloading in runtime (maybe on keybinding like "configs refresh"?

There are some configuration options that only are checked when the emulator starts, things like machine type are 'locked in' for the runtime of the emulator.  I am still thinking about better ways to define machines, especially with plans to support more varied machines in the future (PCjr, Tandy, AT, etc), so this could change and eventually be exposed in the GUI, but it is what it is for now.   I could allow you to reload the config while running but it might be confusing about which config options would apply and which would not.

**Comment by dbalsom** [comment]
I have implemented selectable display profiles for each supported video card in [0.2.0](https://github.com/dbalsom/martypc/tree/version_0_2_0) that will allow you to choose between the full display extents and no overscan whatsoever. There's also a new display scaling option that will fit to the entire window. No more borders if you don't want them!
