### ISSUE TITLE
ST2 halting

### ISSUE THREAD

**Issue by RepellantMold** [dbalsom/martypc#68]
**Describe the bug**
Scream Tracker 2 (~2.2 and~ (ended up entirely forgetting to test 2.2, guess I was impatient and made a false memory of me thinking I tested that version..) 2.3 tested) crashes MartyPC with "The CPU was halted at address: 032E1A" (confirmed on both latest release and on the `new_ega` branch, I also tested using NANSI.SYS via FreeDOS, it halts at 033BEA, standard MS-DOS 3 also halts)

**To Reproduce**
1. [Get a copy of (Scream Tracker 2)](https://ftp.modland.com/pub/software/trackers/DOS/Scream%20Tracker%202/)
2. Get it onto a VHD
3. Extract the zip into a directory called "ST"
4. Change directory into "ST", then type "ST" to run...
5. Look at console;
```
[2023-11-26T15:53:08Z ERROR marty_core::machine] CPU Halted!
[2023-11-26T15:53:08Z ERROR marty_core::machine] CPU Error: The CPU was halted at address: 032E1A.
```

**Expected behavior**
The program should start up to this screen (my color scheme is different though shouldn't matter, screenshotted using DOSBox-X then aspect corrected using paint.net)
![st_000](https://github.com/dbalsom/martypc/assets/76079717/acb08ceb-b12b-4cbd-937d-b4b68cc27a6c)

**Screenshots**
![Screenshot 2023-11-26 074825](https://github.com/dbalsom/martypc/assets/76079717/828895f7-7b7c-40c4-98b3-ef8ebdba481e)

**Environment (please complete the following information):**
 - Windows 11 22H2
 - 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
 - NVIDIA GeForce GTX 1650 SUPER

**Build info**
  - Built from commit `a189d6e` on new_ega
  - Tested on latest release (commit `f6b59ae`)
  - Tested both with turbo mode on and off on both

**Comment by dbalsom** [comment]
MartyPC isn't crashing here, by the looks of it - it is telling you that the emulated CPU has entered an unrecoverable halt (Executed a HLT instruction with interrupts disabled). This is a convenience feature so you don't waste your time waiting for something to happen when nothing ever will.

I tried it on my 5150, and it seems to lock up as well, but I do see "Loading setup..." first, however stopping at a HLT also stops the CGA from drawing so we often miss seeing a string that might have printed out first. I need to fix that...I think I'll just leave the popup that tells you the system halted, but continue to run the system bus.

I suspect this title likely requires a 286. ST1 docs strongly suggested a 10Mhz AT, and ST3 docs say it requires a 386, although ST2 readme doesn't really say what it requires. 

If you want to check something should run on MartyPC, use PCE, PCem or 86box configured to be an 8088 CPU. DosBox emulates a sort of generic, 32-bit x86 chip and so will run things that an original IBM PC never could. If you're willing to test that out it would be a great help, otherwise it will have to wait until I can get to it. I'm afraid even if it can be made to run it will run very poorly on an 8088.

**Comment by RepellantMold** [comment]
Okay so I tried this on 86Box using the "IBM XT (1986)" preset (8088 at both 4.77 and 7.16), used the same FreeDOS then MS-DOS 3 setup, it seems to be running...

https://github.com/dbalsom/martypc/assets/76079717/6b509f1a-4627-40af-b4c8-b6a23c834451

the video shows me running the program, running one of my songs, then expectedly crashing it which I fully expected since the lowest speed for playback for PC speaker (which is all I can test cause no Sound Blaster or Covox DAC support, those go down to 5 Mhz) is 8 Mhz.

**Comment by qeeg** [comment]
I mean, if a program locks up on real hardware, but not in emulators, it's a bug in the emulators. MartyPC is probably correct here.

**Comment by dbalsom** [comment]
Thanks for trying it on 86box. Just curious - what video adapter did you have configured?

**Comment by lautis0503** [comment]
Tried Scream Tracker 2.2 and 2.3 in PCE (5150, 82OCT27 ROM, 8088, CGA, 640K RAM).
Both version start to the main screen. Then ST 2.2 hangs when quiting. And ST 2.3 quits but reports
 `run-time error R6001`
`- null pointer assignment`

**Comment by RepellantMold** [comment]
> Thanks for trying it on 86box. Just curious - what video adapter did you have configured?

"[ISA] CGA"

**Comment by lautis0503** [comment]
Tried Scream Tracker 2.2 and 2.3 in 86Box 4.0.1
Machine: 5150, 82OCT27 ROM, 640K RAM, CGA
OS: PC-DOS 3.30
Same behaviour like in PCE.

I don't know this software. Just a test.

**Comment by lautis0503** [comment]
> I mean, if a program locks up on real hardware, but not in emulators, it's a bug in the emulators. MartyPC is probably correct here.

Maybe run on specific configurations. Not sure.

**Comment by lautis0503** [comment]
ST 2.2 and 2.3 in PCem v17 behaviour the same like in PCE and 86Box.
ST 2.2 in PCjs (5160, 82NOV08 ROM, 8088, CGA, 640K RAM, PC-DOS 3.30) runs, and writes trash characters after quiting. ST 2.3 in PCjs cause CPU halted. `Undefined opcode 0xFF at 0x000F360E`

**Comment by dbalsom** [comment]
ST 2.2 now runs
![image](https://github.com/dbalsom/martypc/assets/7229541/2c0b22f3-5101-475f-bcdb-7429beca8a22)

It even quits without hanging!

ST 2.3 still prints an error message and halts, but it does the same on my real IBM 5150, so I am inclined to say that is accurate
