### ISSUE TITLE
cargo run -r fails to compile on branch

### ISSUE THREAD

**Issue by rationalism** [dbalsom/martypc#78]
On the new branch `version_0_2_0` (commit `0965525ec11cfbcce9012b2f0674bb6c3ed76214`), the command `cargo run -r` in the `install` directory causes compilation to fail, with this error:

```
error[E0446]: private type `MouseData` in public interface
   --> frontends/martypc_desktop_wgpu/src/emulator/mod.rs:71:5
    |
71  |     pub mouse_data: MouseData,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak private type
    |
   ::: frontends/martypc_desktop_wgpu/src/lib.rs:166:1
    |
166 | struct MouseData {
    | ---------------- `MouseData` declared as private

error[E0446]: private type `KeyboardData` in public interface
   --> frontends/martypc_desktop_wgpu/src/emulator/mod.rs:72:5
    |
72  |     pub kb_data: KeyboardData,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak private type
    |
   ::: frontends/martypc_desktop_wgpu/src/lib.rs:216:1
    |
216 | struct KeyboardData {
    | ------------------- `KeyboardData` declared as private

error[E0446]: private type `Counter` in public interface
  --> frontends/martypc_desktop_wgpu/src/emulator/mod.rs:73:5
   |
73 |     pub stat_counter: Counter,
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^ can't leak private type
   |
  ::: frontends/martypc_desktop_wgpu/src/lib.rs:95:1
   |
95 | struct Counter {
   | -------------- `Counter` declared as private
```

@dbalsom

**Comment by lautis0503** [comment]
Same here. I said that two weeks ago in #73 .

**Comment by dbalsom** [comment]
i haven't been able to repro this
```
cargo build -r --features=ega

... snip ...

warning: `martypc_pixels_desktop` (lib) generated 3 warnings (run `cargo fix --lib -p martypc_pixels_desktop` to apply 1 suggestion)
    Finished release [optimized] target(s) in 17.32s

D:\newdev\my_projects\marty\install>cargo --version
cargo 1.74.1 (ecb9851af 2023-10-18)

D:\newdev\my_projects\marty\install>rustc -V
rustc 1.74.1 (a28077b28 2023-12-04)

```

that said i do see what it is complaining about and think i can fix it. i just don't know why it's not  complaining to ME.

**Comment by dbalsom** [comment]
@rationalism @lautis0503 can you try it now

**Comment by rationalism** [comment]
@dbalsom Works now! However, I have to manually create a bunch of directories in `output/` for the provided config file to work

**Comment by dbalsom** [comment]
Side effect of reorganizing some things and Git not checking in empty folders. 
I think the reasonable thing to do is to have the emulator create the specified folders if they don't exist.

**Comment by lautis0503** [comment]
It works. Something confuses me: Why sometimes use `[[]]` and sometimes `[]` in configurations?

And something related to configs.
`[2023-12-26T......Z ERROR martypc_pixels_desktop::emulator] Number of videocards installed does not match number of cards in config!`
What I have is `config_name = "ibm5160_hdd"` and there's `[[overlay.video]]` in my overlay. What's wrong?

**Comment by lautis0503** [comment]
The vhd file defined in martypc.toml or overlay is not selected in Menu->Media->Load VHD in Drive 0.

If I define 256K memory in overlay
`[overlay.memory]`
`conventional.size = 0x40000`
MartyPC still provide 640K memory.
It works correctly if I define memory in machine config file, not in overlay.

**Comment by lautis0503** [comment]
One thing to consider. If there's two floppy drives in machine config, and then I write two floppy drives in overlay. Is there totally four drives or only the two in overlay take effect? I have not checked the source code yet. Maybe it's better to add drive number like PCE does.

**Comment by lautis0503** [comment]
The vhd filename in machine config does not take effect? If I do not specify filename from martypc.toml, then the vhd file is not loaded.

**Comment by dbalsom** [comment]
Please bear in mind that this is all under active development and a lot of this stuff isn't finished. Sorry if that is frustrating but I do appreciate you kicking the tires, so to speak.
 

> Something confuses me: Why sometimes use [[]] and sometimes [] in configurations?

basic TOML grammar. see https://toml.io/en/
in short, double brackets indicate an array of items. so you will have [[thing]] wherever you might have multiple Things at the same time.  Deserialized in Rust, they become Vectors.

> And something related to configs. `[2023-12-26T......Z ERROR martypc_pixels_desktop::emulator] Number of videocards installed does not match number of cards in config!` What I have is `config_name = "ibm5160_hdd"` and there's `[[overlay.video]]` in my overlay. What's wrong?

It's a remnant of reading video cards from the main config, since there shouldn't be any cards in there now it will install more (from machine config) then are in the main config (0) and thus get worried.  i will remove all the video card stuff from the main config as it should all now be handled by machine configuration and overlays.

> The vhd file defined in martypc.toml or overlay is not selected in Menu->Media->Load VHD in Drive 0.

not implemented yet. VHD menu is going to be rewritten with the new resource manager / file browser

> It works correctly if I define memory in machine config file, not in overlay.

it's not implemented. overlays can add various cards, but not conventional memory. i think it would be useful to add though, especially since memory could have been added via expansion card.  eventually i suppose i should specify how much on-board memory vs expansion card memory there is, because in theory it could have different wait states (especially on platforms like PCJr)

> One thing to consider. If there's two floppy drives in machine config, and then I write two floppy drives in overlay. Is there totally four drives or only the two in overlay take effect? I have not checked the source code yet. Maybe it's better to add drive number like PCE does.

You cannot overlay floppies by themselves, you overlay floppy drive controller(s) which have drives defined/connected to it.  So the number of drives will be entirely determined by the number specified in the overlay. Any array of items will work the same way, so you cannot say, add a second video card to an existing video card in an overlay, you will replace all video cards if you specify 1 or more video cards in an overlay.  So to have dual CGA and MDA you can see I defined a "cga_and_mda" overlay.

if there's a better way to handle this i'm willing to consider it, but i don't know how best to differentiate replacing a card vs adding an additional card in an overlay definition. let me know if you have an idea.

**Comment by dbalsom** [comment]
VHD support in machine configurations will be a bit awkward now, since you currently have to manually create all VHDs, and it would be up to you to name them the same as the name given in the configuration, and ensure you created it as a compatible type...

so I am thinking if a VHD name is specified in a machine configuration and does not exist, MartyPC should create a compatible VHD automatically when you start the machine. I can make this optional, or maybe prompt for confirmation first

something like
```toml
[emulator.media]
auto_vhd = true
```

**Comment by lautis0503** [comment]
> basic TOML grammar. see https://toml.io/en/

Thanks. I had never read TOML docs before.

> i think it would be useful to add though, especially since memory could have been added via expansion card. eventually i suppose i should specify how much on-board memory vs expansion card memory there is, because in theory it could have different wait states (especially on platforms like PCJr)

Yes, it's useful. I'm using 640K RAM in machine config for all machines, and one of the machines uses 256K RAM in overlay.

> if there's a better way to handle this i'm willing to consider it, but i don't know how best to differentiate replacing a card vs adding an additional card in an overlay definition. let me know if you have an idea.

The situation now is good enough. What I want is free of misunderstanding. Later in docs should there be explaination about this behaviour.

**Comment by dbalsom** [comment]
> @dbalsom Works now! However, I have to manually create a bunch of directories in `output/` for the provided config file to work

I have added flags to the path definitions that will instruct MartyPC to create the output folders if they don't exist.
